<?php

use Illuminate\Database\Seeder;

class PkgTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $id =1;
        \App\Pkg::create(['state_id'=>	8	, 'pkg'=>'	PKG Simpang Empat	']);
        \App\Pkg::create(['state_id'=>	8	, 'pkg'=>'	PKG Kayang	']);
        \App\Pkg::create(['state_id'=>	8	, 'pkg'=>'	PKG Kangar	']);
        \App\Pkg::create(['state_id'=>	8	, 'pkg'=>'	PKG Tunjong	']);
        \App\Pkg::create(['state_id'=>	8	, 'pkg'=>'	PKG Jejawi	']);
        \App\Pkg::create(['state_id'=>	8	, 'pkg'=>'	PKG Arau	']);
        \App\Pkg::create(['state_id'=>	8	, 'pkg'=>'	PKG Tambun Tulang	']);
        \App\Pkg::create(['state_id'=>	8	, 'pkg'=>'	PKG Titi Tinggi	']);
        \App\Pkg::create(['state_id'=>	2	, 'pkg'=>'	PKG Hosba	']);
        \App\Pkg::create(['state_id'=>	2	, 'pkg'=>'	PKG Kodiang	']);
        \App\Pkg::create(['state_id'=>	2	, 'pkg'=>'	PKG Kuah	']);
        \App\Pkg::create(['state_id'=>	2	, 'pkg'=>'	PKG Kuala Pegang	']);
        \App\Pkg::create(['state_id'=>	2	, 'pkg'=>'	PKG Langgar	']);
        \App\Pkg::create(['state_id'=>	2	, 'pkg'=>'	PKG Simpang Empat	']);
        \App\Pkg::create(['state_id'=>	2	, 'pkg'=>'	PKG Padang Serai	']);
        \App\Pkg::create(['state_id'=>	2	, 'pkg'=>'	PKG Pendang	']);
        \App\Pkg::create(['state_id'=>	2	, 'pkg'=>'	PKG Serdang	']);
        \App\Pkg::create(['state_id'=>	2	, 'pkg'=>'	PKG Sik	']);
        \App\Pkg::create(['state_id'=>	2	, 'pkg'=>'	PKG Sungai Limau	']);
        \App\Pkg::create(['state_id'=>	2	, 'pkg'=>'	PKG Alor Janggus	']);
        \App\Pkg::create(['state_id'=>	2	, 'pkg'=>'	PKG Baling	']);
        \App\Pkg::create(['state_id'=>	2	, 'pkg'=>'	PKG Bujang	']);
        \App\Pkg::create(['state_id'=>	2	, 'pkg'=>'	PKG Bukit Jenun	']);
        \App\Pkg::create(['state_id'=>	2	, 'pkg'=>'	PKG Bukit Selambau	']);
        \App\Pkg::create(['state_id'=>	2	, 'pkg'=>'	PKG Sungai Ular	']);
        \App\Pkg::create(['state_id'=>	2	, 'pkg'=>'	PKG Gurun	']);
        \App\Pkg::create(['state_id'=>	2	, 'pkg'=>'	PKG Kuala Ketil	']);
        \App\Pkg::create(['state_id'=>	2	, 'pkg'=>'	PKG Bandar Baharu	']);
        \App\Pkg::create(['state_id'=>	2	, 'pkg'=>'	PKG Yan	']);
        \App\Pkg::create(['state_id'=>	2	, 'pkg'=>'	PKG Kuala Nerang	']);
        \App\Pkg::create(['state_id'=>	2	, 'pkg'=>'	PKG Sungai Petani	']);
        \App\Pkg::create(['state_id'=>	2	, 'pkg'=>'	PKG Padang Mat Sirat	']);
        \App\Pkg::create(['state_id'=>	2	, 'pkg'=>'	PKG Tokai	']);
        \App\Pkg::create(['state_id'=>	2	, 'pkg'=>'	PKG Sungai Layar	']);
        \App\Pkg::create(['state_id'=>	2	, 'pkg'=>'	PKG Ayer Hitam	']);
        \App\Pkg::create(['state_id'=>	2	, 'pkg'=>'	PKG Pokok Sena	']);
        \App\Pkg::create(['state_id'=>	2	, 'pkg'=>'	PKG Teluk Kechai	']);
        \App\Pkg::create(['state_id'=>	2	, 'pkg'=>'	PKG Kota Kuala Muda	']);
        \App\Pkg::create(['state_id'=>	2	, 'pkg'=>'	PKG Kulim	']);
        \App\Pkg::create(['state_id'=>	2	, 'pkg'=>'	PKG Tunjang	']);
        \App\Pkg::create(['state_id'=>	9	, 'pkg'=>'	PKG Bukit Mertajam	']);
        \App\Pkg::create(['state_id'=>	9	, 'pkg'=>'	PKG Bayan Lepas	']);
        \App\Pkg::create(['state_id'=>	9	, 'pkg'=>'	PKG Datuk Keramat	']);
        \App\Pkg::create(['state_id'=>	9	, 'pkg'=>'	PKG Penaga	']);
        \App\Pkg::create(['state_id'=>	9	, 'pkg'=>'	PKG Alma	']);
        \App\Pkg::create(['state_id'=>	9	, 'pkg'=>'	PKG Seberang Jaya	']);
        \App\Pkg::create(['state_id'=>	9	, 'pkg'=>'	PKG Penanti	']);
        \App\Pkg::create(['state_id'=>	9	, 'pkg'=>'	PKG Tasek Gelugor	']);
        \App\Pkg::create(['state_id'=>	9	, 'pkg'=>'	PKG Tanjung Bunga	']);
        \App\Pkg::create(['state_id'=>	9	, 'pkg'=>'	PKG Ayer Hitam	']);
        \App\Pkg::create(['state_id'=>	9	, 'pkg'=>'	PKG Sungai Bakap	']);
        \App\Pkg::create(['state_id'=>	9	, 'pkg'=>'	PKG Telok Air Tawar	']);
        \App\Pkg::create(['state_id'=>	9	, 'pkg'=>'	PKG Nibong Tebal	']);
        \App\Pkg::create(['state_id'=>	9	, 'pkg'=>'	PKG Kepala Batas	']);
        \App\Pkg::create(['state_id'=>	9	, 'pkg'=>'	PKG Butterworth	']);
        \App\Pkg::create(['state_id'=>	9	, 'pkg'=>'	PKG Kelawai	']);
        \App\Pkg::create(['state_id'=>	9	, 'pkg'=>'	PKG Balik Pulau	']);
        \App\Pkg::create(['state_id'=>	9	, 'pkg'=>'	PKG Gelugor	']);
        \App\Pkg::create(['state_id'=>	12	, 'pkg'=>'	PKG Pelabuhan KLang	']);
        \App\Pkg::create(['state_id'=>	12	, 'pkg'=>'	PKG Telok Gadong	']);
        \App\Pkg::create(['state_id'=>	12	, 'pkg'=>'	PKG Kapar	']);
        \App\Pkg::create(['state_id'=>	12	, 'pkg'=>'	PKG Klang Bandar	']);
        \App\Pkg::create(['state_id'=>	12	, 'pkg'=>'	PKG Jalan Meru	']);
        \App\Pkg::create(['state_id'=>	12	, 'pkg'=>'	PKG Sijangkang	']);
        \App\Pkg::create(['state_id'=>	12	, 'pkg'=>'	PKG Batu Laut	']);
        \App\Pkg::create(['state_id'=>	12	, 'pkg'=>'	PKG Kanchong Darat	']);
        \App\Pkg::create(['state_id'=>	12	, 'pkg'=>'	PKG Banting	']);
        \App\Pkg::create(['state_id'=>	12	, 'pkg'=>'	PKG Bukit Badong	']);
        \App\Pkg::create(['state_id'=>	12	, 'pkg'=>'	PKG Kuala Selangor	']);
        \App\Pkg::create(['state_id'=>	12	, 'pkg'=>'	PKG Jeram	']);
        \App\Pkg::create(['state_id'=>	12	, 'pkg'=>'	PKG Rantau Panjang	']);
        \App\Pkg::create(['state_id'=>	12	, 'pkg'=>'	PKG Tanjung Karang	']);
        \App\Pkg::create(['state_id'=>	12	, 'pkg'=>'	PKG Cheras	']);
        \App\Pkg::create(['state_id'=>	12	, 'pkg'=>'	PKG Semenyih	']);
        \App\Pkg::create(['state_id'=>	12	, 'pkg'=>'	PKG Bangi	']);
        \App\Pkg::create(['state_id'=>	12	, 'pkg'=>'	PKG Ampang	']);
        \App\Pkg::create(['state_id'=>	12	, 'pkg'=>'	PKG Kajang	']);
        \App\Pkg::create(['state_id'=>	12	, 'pkg'=>'	PKG Kampung Soeharto	']);
        \App\Pkg::create(['state_id'=>	12	, 'pkg'=>'	PKG Kalumpang	']);
        \App\Pkg::create(['state_id'=>	12	, 'pkg'=>'	PKG Sungai Choh	']);
        \App\Pkg::create(['state_id'=>	12	, 'pkg'=>'	PKG Kuala Kubu Bharu	']);
        \App\Pkg::create(['state_id'=>	12	, 'pkg'=>'	PKG Pasir Panjang	']);
        \App\Pkg::create(['state_id'=>	12	, 'pkg'=>'	PKG Sungai Besar	']);
        \App\Pkg::create(['state_id'=>	12	, 'pkg'=>'	PKG Batu 38	']);
        \App\Pkg::create(['state_id'=>	12	, 'pkg'=>'	PKG Sungai Air Tawar	']);
        \App\Pkg::create(['state_id'=>	12	, 'pkg'=>'	PKG Sabak Bernam	']);
        \App\Pkg::create(['state_id'=>	12	, 'pkg'=>'	PKG Gombak	']);
        \App\Pkg::create(['state_id'=>	12	, 'pkg'=>'	PKG Hulu Klang	']);
        \App\Pkg::create(['state_id'=>	12	, 'pkg'=>'	PKG Rawang	']);
        \App\Pkg::create(['state_id'=>	12	, 'pkg'=>'	PKG Kuang	']);
        \App\Pkg::create(['state_id'=>	12	, 'pkg'=>'	PKG Puchong	']);
        \App\Pkg::create(['state_id'=>	12	, 'pkg'=>'	PKG Subang Jaya	']);
        \App\Pkg::create(['state_id'=>	12	, 'pkg'=>'	PKG Sungai Pelek	']);
        \App\Pkg::create(['state_id'=>	12	, 'pkg'=>'	PKG Salak	']);
        \App\Pkg::create(['state_id'=>	15	, 'pkg'=>'	PKG Rancha-Rancha	']);
        \App\Pkg::create(['state_id'=>	1	, 'pkg'=>'	PKG Parit Sulong	']);
        \App\Pkg::create(['state_id'=>	1	, 'pkg'=>'	PKG Senggarang	']);
        \App\Pkg::create(['state_id'=>	1	, 'pkg'=>'	PKG Air Hitam	']);
        \App\Pkg::create(['state_id'=>	1	, 'pkg'=>'	PKG Yong Peng	']);
        \App\Pkg::create(['state_id'=>	1	, 'pkg'=>'	PKG Seri Medan	']);
        \App\Pkg::create(['state_id'=>	1	, 'pkg'=>'	PKG Parit Raja	']);
        \App\Pkg::create(['state_id'=>	1	, 'pkg'=>'	PKG Bagan	']);
        \App\Pkg::create(['state_id'=>	1	, 'pkg'=>'	PKG Penggaram	']);
        \App\Pkg::create(['state_id'=>	1	, 'pkg'=>'	PKG Tongkang Pechah	']);
        \App\Pkg::create(['state_id'=>	1	, 'pkg'=>'	PKG Kompleks Uda	']);
        \App\Pkg::create(['state_id'=>	1	, 'pkg'=>'	PKG Gelang Patah	']);
        \App\Pkg::create(['state_id'=>	1	, 'pkg'=>'	PKG Tasek Utara	']);
        \App\Pkg::create(['state_id'=>	1	, 'pkg'=>'	PKG Majidee	']);
        \App\Pkg::create(['state_id'=>	1	, 'pkg'=>'	PKG Pasir Gudang	']);
        \App\Pkg::create(['state_id'=>	1	, 'pkg'=>'	PKG Ulu Tiram	']);
        \App\Pkg::create(['state_id'=>	1	, 'pkg'=>'	PKG Permas Jaya	']);
        \App\Pkg::create(['state_id'=>	1	, 'pkg'=>'	PKG Bandar Renggam	']);
        \App\Pkg::create(['state_id'=>	1	, 'pkg'=>'	PKG Bandar Kluang	']);
        \App\Pkg::create(['state_id'=>	1	, 'pkg'=>'	PKG Kluang Timur	']);
        \App\Pkg::create(['state_id'=>	1	, 'pkg'=>'	PKG Bandar Paloh	']);
        \App\Pkg::create(['state_id'=>	1	, 'pkg'=>'	PKG Bandar Kota Tinggi	']);
        \App\Pkg::create(['state_id'=>	1	, 'pkg'=>'	PKG Pengerang	']);
        \App\Pkg::create(['state_id'=>	1	, 'pkg'=>'	PKG Bandar Mas	']);
        \App\Pkg::create(['state_id'=>	1	, 'pkg'=>'	PKG Bandar Mersing	']);
        \App\Pkg::create(['state_id'=>	1	, 'pkg'=>'	PKG Endau	']);
        \App\Pkg::create(['state_id'=>	1	, 'pkg'=>'	PKG Parit Bunga	']);
        \App\Pkg::create(['state_id'=>	1	, 'pkg'=>'	PKG Tangkak	']);
        \App\Pkg::create(['state_id'=>	1	, 'pkg'=>'	PKG Bakri	']);
        \App\Pkg::create(['state_id'=>	1	, 'pkg'=>'	PKG Bukit Gambir	']);
        \App\Pkg::create(['state_id'=>	1	, 'pkg'=>'	PKG Sungai Balang	']);
        \App\Pkg::create(['state_id'=>	1	, 'pkg'=>'	PKG Lenga	']);
        \App\Pkg::create(['state_id'=>	1	, 'pkg'=>'	PKG Jalan Tunku Bendahara	']);
        \App\Pkg::create(['state_id'=>	1	, 'pkg'=>'	PKG Serom	']);
        \App\Pkg::create(['state_id'=>	1	, 'pkg'=>'	PKG Parit Setongkat	']);
        \App\Pkg::create(['state_id'=>	1	, 'pkg'=>'	PKG Parit Jawa	']);
        \App\Pkg::create(['state_id'=>	1	, 'pkg'=>'	PKG Kukup	']);
        \App\Pkg::create(['state_id'=>	1	, 'pkg'=>'	PKG Pekan Nanas	']);
        \App\Pkg::create(['state_id'=>	1	, 'pkg'=>'	PKG Bandar Pontian	']);
        \App\Pkg::create(['state_id'=>	1	, 'pkg'=>'	PKG Benut	']);
        \App\Pkg::create(['state_id'=>	1	, 'pkg'=>'	PKG Buloh Kasap	']);
        \App\Pkg::create(['state_id'=>	1	, 'pkg'=>'	PKG Bandar Segamat	']);
        \App\Pkg::create(['state_id'=>	1	, 'pkg'=>'	PKG Labis	']);
        \App\Pkg::create(['state_id'=>	1	, 'pkg'=>'	PKG Segamat Baru	']);
        \App\Pkg::create(['state_id'=>	1	, 'pkg'=>'	PKG Sungai Sayong	']);
        \App\Pkg::create(['state_id'=>	1	, 'pkg'=>'	PKG Bandar Kulai	']);
        \App\Pkg::create(['state_id'=>	7	, 'pkg'=>'	PKG Taiping	']);
        \App\Pkg::create(['state_id'=>	7	, 'pkg'=>'	PKG Seri Ampang	']);
        \App\Pkg::create(['state_id'=>	7	, 'pkg'=>'	PKG Seberang Perak	']);
        \App\Pkg::create(['state_id'=>	7	, 'pkg'=>'	PKG Talang	']);
        \App\Pkg::create(['state_id'=>	7	, 'pkg'=>'	PKG Slim River	']);
        \App\Pkg::create(['state_id'=>	7	, 'pkg'=>'	PKG Sungai Pari	']);
        \App\Pkg::create(['state_id'=>	7	, 'pkg'=>'	PKG Dato Panglima Kinta	']);
        \App\Pkg::create(['state_id'=>	7	, 'pkg'=>'	PKG Kota Lama Kanan	']);
        \App\Pkg::create(['state_id'=>	7	, 'pkg'=>'	PKG Sungkai	']);
        \App\Pkg::create(['state_id'=>	7	, 'pkg'=>'	PKG Parit Buntar	']);
        \App\Pkg::create(['state_id'=>	7	, 'pkg'=>'	PKG Kampung Gajah	']);
        \App\Pkg::create(['state_id'=>	7	, 'pkg'=>'	PKG Beruas	']);
        \App\Pkg::create(['state_id'=>	7	, 'pkg'=>'	PKG Temoh	']);
        \App\Pkg::create(['state_id'=>	7	, 'pkg'=>'	PKG Lahat	']);
        \App\Pkg::create(['state_id'=>	7	, 'pkg'=>'	PKG Ayer Tawar	']);
        \App\Pkg::create(['state_id'=>	7	, 'pkg'=>'	PKG Teluk Intan	']);
        \App\Pkg::create(['state_id'=>	7	, 'pkg'=>'	PKG Bagan Datoh	']);
        \App\Pkg::create(['state_id'=>	7	, 'pkg'=>'	PKG Sungai Siput	']);
        \App\Pkg::create(['state_id'=>	7	, 'pkg'=>'	PKG Tapah Road	']);
        \App\Pkg::create(['state_id'=>	7	, 'pkg'=>'	PKG Kampar	']);
        \App\Pkg::create(['state_id'=>	7	, 'pkg'=>'	PKG Simpang	']);
        \App\Pkg::create(['state_id'=>	7	, 'pkg'=>'	PKG Seri Manjung	']);
        \App\Pkg::create(['state_id'=>	7	, 'pkg'=>'	PKG Kati	']);
        \App\Pkg::create(['state_id'=>	7	, 'pkg'=>'	PKG Tanjung Tualang	']);
        \App\Pkg::create(['state_id'=>	7	, 'pkg'=>'	PKG Gunung Semanggol	']);
        \App\Pkg::create(['state_id'=>	7	, 'pkg'=>'	PKG Kamunting	']);
        \App\Pkg::create(['state_id'=>	7	, 'pkg'=>'	PKG Trong	']);
        \App\Pkg::create(['state_id'=>	7	, 'pkg'=>'	PKG Parit	']);
        \App\Pkg::create(['state_id'=>	7	, 'pkg'=>'	PKG Tasek	']);
        \App\Pkg::create(['state_id'=>	7	, 'pkg'=>'	PKG Teluk Medan	']);
        \App\Pkg::create(['state_id'=>	7	, 'pkg'=>'	PKG Batu Gajah	']);
        \App\Pkg::create(['state_id'=>	7	, 'pkg'=>'	PKG Tanjong Malim	']);
        \App\Pkg::create(['state_id'=>	7	, 'pkg'=>'	PKG Sitiawan	']);
        \App\Pkg::create(['state_id'=>	7	, 'pkg'=>'	PKG Manjoi	']);
        \App\Pkg::create(['state_id'=>	7	, 'pkg'=>'	PKG Lenggong	']);
        \App\Pkg::create(['state_id'=>	7	, 'pkg'=>'	PKG Bidor	']);
        \App\Pkg::create(['state_id'=>	7	, 'pkg'=>'	PKG Gopeng	']);
        \App\Pkg::create(['state_id'=>	7	, 'pkg'=>'	PKG Batu Kurau	']);
        \App\Pkg::create(['state_id'=>	7	, 'pkg'=>'	PKG Chenderong Balai	']);
        \App\Pkg::create(['state_id'=>	7	, 'pkg'=>'	PKG Pantai Remis	']);
        \App\Pkg::create(['state_id'=>	7	, 'pkg'=>'	PKG Grik	']);
        \App\Pkg::create(['state_id'=>	7	, 'pkg'=>'	PKG Hutan Melintang	']);
        \App\Pkg::create(['state_id'=>	7	, 'pkg'=>'	PKG Langkap	']);
        \App\Pkg::create(['state_id'=>	7	, 'pkg'=>'	PKG Pengkalan Hulu	']);
        \App\Pkg::create(['state_id'=>	7	, 'pkg'=>'	PKG Bota	']);
        \App\Pkg::create(['state_id'=>	7	, 'pkg'=>'	PKG Selama	']);
        \App\Pkg::create(['state_id'=>	7	, 'pkg'=>'	PKG Selekoh	']);
        \App\Pkg::create(['state_id'=>	7	, 'pkg'=>'	PKG Bagan Serai	']);
        \App\Pkg::create(['state_id'=>	7	, 'pkg'=>'	PKG Manong	']);
        \App\Pkg::create(['state_id'=>	7	, 'pkg'=>'	PKG Kuala Kurau	']);
        \App\Pkg::create(['state_id'=>	10	, 'pkg'=>'	PKG Tambunan	']);
        \App\Pkg::create(['state_id'=>	10	, 'pkg'=>'	PKG Sipitang	']);
        \App\Pkg::create(['state_id'=>	10	, 'pkg'=>'	PKG Semporna	']);
        \App\Pkg::create(['state_id'=>	10	, 'pkg'=>'	PKG Keningau	']);
        \App\Pkg::create(['state_id'=>	10	, 'pkg'=>'	PKG Kinabatangan	']);
        \App\Pkg::create(['state_id'=>	10	, 'pkg'=>'	PKG Kudat	']);
        \App\Pkg::create(['state_id'=>	10	, 'pkg'=>'	PKG Kuala Penyu	']);
        \App\Pkg::create(['state_id'=>	10	, 'pkg'=>'	PKG Papar	']);
        \App\Pkg::create(['state_id'=>	10	, 'pkg'=>'	PKG Ranau	']);
        \App\Pkg::create(['state_id'=>	10	, 'pkg'=>'	PKG Pitas	']);
        \App\Pkg::create(['state_id'=>	10	, 'pkg'=>'	PKG Lahad Datu	']);
        \App\Pkg::create(['state_id'=>	10	, 'pkg'=>'	PKG Tuaran	']);
        \App\Pkg::create(['state_id'=>	10	, 'pkg'=>'	PKG Sandakan	']);
        \App\Pkg::create(['state_id'=>	10	, 'pkg'=>'	PKG Beluran	']);
        \App\Pkg::create(['state_id'=>	10	, 'pkg'=>'	PKG Tenom	']);
        \App\Pkg::create(['state_id'=>	10	, 'pkg'=>'	PKG Beaufort	']);
        \App\Pkg::create(['state_id'=>	10	, 'pkg'=>'	PKG Kota Belud	']);
        \App\Pkg::create(['state_id'=>	10	, 'pkg'=>'	PKG Kota Kinabalu	']);
        \App\Pkg::create(['state_id'=>	10	, 'pkg'=>'	PKG Kota Marudu	']);
        \App\Pkg::create(['state_id'=>	10	, 'pkg'=>'	PKG Kunak	']);
        \App\Pkg::create(['state_id'=>	10	, 'pkg'=>'	PKG Membakut	']);
        \App\Pkg::create(['state_id'=>	10	, 'pkg'=>'	PKG Nabawan	']);
        \App\Pkg::create(['state_id'=>	10	, 'pkg'=>'	PKG Penampang	']);
        \App\Pkg::create(['state_id'=>	10	, 'pkg'=>'	PKG Tamparuli	']);
        \App\Pkg::create(['state_id'=>	10	, 'pkg'=>'	PKG Tawau	']);
        \App\Pkg::create(['state_id'=>	10	, 'pkg'=>'	PKG Telupid	']);
        \App\Pkg::create(['state_id'=>	14	, 'pkg'=>'	PKG Segambut Jaya	']);
        \App\Pkg::create(['state_id'=>	14	, 'pkg'=>'	PKG Bangsar	']);
        \App\Pkg::create(['state_id'=>	14	, 'pkg'=>'	PKG Pudu	']);
        \App\Pkg::create(['state_id'=>	14	, 'pkg'=>'	PKG Keramat	']);
        \App\Pkg::create(['state_id'=>	14	, 'pkg'=>'	PKG Sentul	']);
        \App\Pkg::create(['state_id'=>	14	, 'pkg'=>'	PKG Kampung Pandan	']);
        \App\Pkg::create(['state_id'=>	4	, 'pkg'=>'	PKG Ayer Molek	']);
        \App\Pkg::create(['state_id'=>	4	, 'pkg'=>'	PKG Jasin	']);
        \App\Pkg::create(['state_id'=>	4	, 'pkg'=>'	PKG Ganun	']);
        \App\Pkg::create(['state_id'=>	4	, 'pkg'=>'	PKG Cheng	']);
        \App\Pkg::create(['state_id'=>	4	, 'pkg'=>'	PKG Kampung Gelam	']);
        \App\Pkg::create(['state_id'=>	4	, 'pkg'=>'	PKG Melekek	']);
        \App\Pkg::create(['state_id'=>	4	, 'pkg'=>'	PKG Sebatu	']);
        \App\Pkg::create(['state_id'=>	4	, 'pkg'=>'	PKG Alor Gajah	']);
        \App\Pkg::create(['state_id'=>	4	, 'pkg'=>'	PKG Bachang	']);
        \App\Pkg::create(['state_id'=>	4	, 'pkg'=>'	PKG Padang Temu	']);
        \App\Pkg::create(['state_id'=>	4	, 'pkg'=>'	PKG Masjid Baru	']);
        \App\Pkg::create(['state_id'=>	4	, 'pkg'=>'	PKG Masjid Tanah	']);
        \App\Pkg::create(['state_id'=>	4	, 'pkg'=>'	PKG Pengkalan Balak	']);
        \App\Pkg::create(['state_id'=>	4	, 'pkg'=>'	PKG Batu Berendam	']);
        \App\Pkg::create(['state_id'=>	4	, 'pkg'=>'	PKG Selandar	']);
        \App\Pkg::create(['state_id'=>	4	, 'pkg'=>'	PKG Serkam	']);
        \App\Pkg::create(['state_id'=>	3	, 'pkg'=>'	PKG Kota	']);
        \App\Pkg::create(['state_id'=>	3	, 'pkg'=>'	PKG Banggol	']);
        \App\Pkg::create(['state_id'=>	3	, 'pkg'=>'	PKG Tapang	']);
        \App\Pkg::create(['state_id'=>	3	, 'pkg'=>'	PKG Ketereh	']);
        \App\Pkg::create(['state_id'=>	3	, 'pkg'=>'	PKG Mekasar	']);
        \App\Pkg::create(['state_id'=>	3	, 'pkg'=>'	PKG Kangkong	']);
        \App\Pkg::create(['state_id'=>	3	, 'pkg'=>'	PKG Kedai Tanjong	']);
        \App\Pkg::create(['state_id'=>	3	, 'pkg'=>'	PKG Rantau Panjang	']);
        \App\Pkg::create(['state_id'=>	3	, 'pkg'=>'	PKG Pasir Pekan	']);
        \App\Pkg::create(['state_id'=>	3	, 'pkg'=>'	PKG Tumpat	']);
        \App\Pkg::create(['state_id'=>	3	, 'pkg'=>'	PKG Chabang Empat	']);
        \App\Pkg::create(['state_id'=>	3	, 'pkg'=>'	PKG Cherang Ruku	']);
        \App\Pkg::create(['state_id'=>	3	, 'pkg'=>'	PKG Gaal	']);
        \App\Pkg::create(['state_id'=>	3	, 'pkg'=>'	PKG Bukit Jawa	']);
        \App\Pkg::create(['state_id'=>	3	, 'pkg'=>'	PKG Labok	']);
        \App\Pkg::create(['state_id'=>	3	, 'pkg'=>'	PKG Jambu Lawar	']);
        \App\Pkg::create(['state_id'=>	3	, 'pkg'=>'	PKG Machang	']);
        \App\Pkg::create(['state_id'=>	3	, 'pkg'=>'	PKG Ipoh	']);
        \App\Pkg::create(['state_id'=>	3	, 'pkg'=>'	PKG Ayer Lanas	']);
        \App\Pkg::create(['state_id'=>	3	, 'pkg'=>'	PKG Jeli	']);
        \App\Pkg::create(['state_id'=>	3	, 'pkg'=>'	PKG Bedal	']);
        \App\Pkg::create(['state_id'=>	3	, 'pkg'=>'	PKG Pahi	']);
        \App\Pkg::create(['state_id'=>	3	, 'pkg'=>'	PKG Dabong	']);
        \App\Pkg::create(['state_id'=>	3	, 'pkg'=>'	PKG Gua Musang	']);
        \App\Pkg::create(['state_id'=>	3	, 'pkg'=>'	PKG Beris Kubor Besar	']);
        \App\Pkg::create(['state_id'=>	3	, 'pkg'=>'	PKG Kampung Chap	']);
        \App\Pkg::create(['state_id'=>	3	, 'pkg'=>'	PKG Badak	']);
        \App\Pkg::create(['state_id'=>	5	, 'pkg'=>'	PKG Tanjung Ipoh	']);
        \App\Pkg::create(['state_id'=>	5	, 'pkg'=>'	PKG Rembau	']);
        \App\Pkg::create(['state_id'=>	5	, 'pkg'=>'	PKG Pertang	']);
        \App\Pkg::create(['state_id'=>	5	, 'pkg'=>'	PKG Chuah	']);
        \App\Pkg::create(['state_id'=>	5	, 'pkg'=>'	PKG Nilai	']);
        \App\Pkg::create(['state_id'=>	5	, 'pkg'=>'	PKG Tampin	']);
        \App\Pkg::create(['state_id'=>	5	, 'pkg'=>'	PKG Kota	']);
        \App\Pkg::create(['state_id'=>	5	, 'pkg'=>'	PKG Rantau	']);
        \App\Pkg::create(['state_id'=>	5	, 'pkg'=>'	PKG Rompin	']);
        \App\Pkg::create(['state_id'=>	5	, 'pkg'=>'	PKG Johol	']);
        \App\Pkg::create(['state_id'=>	5	, 'pkg'=>'	PKG Bahau	']);
        \App\Pkg::create(['state_id'=>	5	, 'pkg'=>'	PKG Batu Kikir	']);
        \App\Pkg::create(['state_id'=>	5	, 'pkg'=>'	PKG Gemas	']);
        \App\Pkg::create(['state_id'=>	5	, 'pkg'=>'	PKG Kuala Pilah	']);
        \App\Pkg::create(['state_id'=>	5	, 'pkg'=>'	PKG Port Dickson	']);
        \App\Pkg::create(['state_id'=>	5	, 'pkg'=>'	PKG Mantin	']);
        \App\Pkg::create(['state_id'=>	5	, 'pkg'=>'	PKG Mambau	']);
        \App\Pkg::create(['state_id'=>	5	, 'pkg'=>'	PKG Ampangan	']);
        \App\Pkg::create(['state_id'=>	5	, 'pkg'=>'	PKG Gemencheh	']);
        \App\Pkg::create(['state_id'=>	5	, 'pkg'=>'	PKG Kuala Klawang	']);
        \App\Pkg::create(['state_id'=>	5	, 'pkg'=>'	PKG Lui	']);
        \App\Pkg::create(['state_id'=>	6	, 'pkg'=>'	PKG Kuala Krau	']);
        \App\Pkg::create(['state_id'=>	6	, 'pkg'=>'	PKG Batu Talam	']);
        \App\Pkg::create(['state_id'=>	6	, 'pkg'=>'	PKG Teruntum	']);
        \App\Pkg::create(['state_id'=>	6	, 'pkg'=>'	PKG Bandar Temerloh	']);
        \App\Pkg::create(['state_id'=>	6	, 'pkg'=>'	PKG Lanchang	']);
        \App\Pkg::create(['state_id'=>	6	, 'pkg'=>'	PKG Temin	']);
        \App\Pkg::create(['state_id'=>	6	, 'pkg'=>'	PKG Jengka	']);
        \App\Pkg::create(['state_id'=>	6	, 'pkg'=>'	PKG Triang	']);
        \App\Pkg::create(['state_id'=>	6	, 'pkg'=>'	PKG Bandar Pusat Jengka	']);
        \App\Pkg::create(['state_id'=>	6	, 'pkg'=>'	PKG Bandar Mentakab	']);
        \App\Pkg::create(['state_id'=>	6	, 'pkg'=>'	PKG Bandar Rompin	']);
        \App\Pkg::create(['state_id'=>	6	, 'pkg'=>'	PKG Pelangai	']);
        \App\Pkg::create(['state_id'=>	6	, 'pkg'=>'	PKG Tahan	']);
        \App\Pkg::create(['state_id'=>	6	, 'pkg'=>'	PKG Keratong	']);
        \App\Pkg::create(['state_id'=>	6	, 'pkg'=>'	PKG Muadzam Shah	']);
        \App\Pkg::create(['state_id'=>	6	, 'pkg'=>'	PKG Cameron Highlands	']);
        \App\Pkg::create(['state_id'=>	6	, 'pkg'=>'	PKG Karak	']);
        \App\Pkg::create(['state_id'=>	6	, 'pkg'=>'	PKG Dong	']);
        \App\Pkg::create(['state_id'=>	6	, 'pkg'=>'	PKG Chenor	']);
        \App\Pkg::create(['state_id'=>	6	, 'pkg'=>'	PKG Gelanggi	']);
        \App\Pkg::create(['state_id'=>	6	, 'pkg'=>'	PKG Bandar Raub	']);
        \App\Pkg::create(['state_id'=>	6	, 'pkg'=>'	PKG Bandar Jerantut	']);
        \App\Pkg::create(['state_id'=>	6	, 'pkg'=>'	PKG Bandar Bentong	']);
        \App\Pkg::create(['state_id'=>	6	, 'pkg'=>'	PKG Jaya Gading	']);
        \App\Pkg::create(['state_id'=>	6	, 'pkg'=>'	PKG Bera	']);
        \App\Pkg::create(['state_id'=>	6	, 'pkg'=>'	PKG Benta	']);
        \App\Pkg::create(['state_id'=>	6	, 'pkg'=>'	PKG Bandar Maran	']);
        \App\Pkg::create(['state_id'=>	6	, 'pkg'=>'	PKG Jalan Sg Lembing	']);
        \App\Pkg::create(['state_id'=>	6	, 'pkg'=>'	PKG Bandar Pekan	']);
        \App\Pkg::create(['state_id'=>	6	, 'pkg'=>'	PKG Pantai	']);
        \App\Pkg::create(['state_id'=>	6	, 'pkg'=>'	PKG Kuala Lipis	']);
        \App\Pkg::create(['state_id'=>	6	, 'pkg'=>'	PKG Tembeling	']);
        \App\Pkg::create(['state_id'=>	6	, 'pkg'=>'	PKG Padang Tengku	']);
        \App\Pkg::create(['state_id'=>	11	, 'pkg'=>'	PKG Kuching	']);
        \App\Pkg::create(['state_id'=>	11	, 'pkg'=>'	PKG Serian	']);
        \App\Pkg::create(['state_id'=>	11	, 'pkg'=>'	PKG Bau	']);
        \App\Pkg::create(['state_id'=>	11	, 'pkg'=>'	PKG Lundu	']);
        \App\Pkg::create(['state_id'=>	11	, 'pkg'=>'	PKG Simunjan	']);
        \App\Pkg::create(['state_id'=>	11	, 'pkg'=>'	PKG Sri Aman	']);
        \App\Pkg::create(['state_id'=>	11	, 'pkg'=>'	PKG Lubok Antu	']);
        \App\Pkg::create(['state_id'=>	11	, 'pkg'=>'	PKG Betong	']);
        \App\Pkg::create(['state_id'=>	11	, 'pkg'=>'	PKG Saratok	']);
        \App\Pkg::create(['state_id'=>	11	, 'pkg'=>'	PKG Sibu	']);
        \App\Pkg::create(['state_id'=>	11	, 'pkg'=>'	PKG Kanowit	']);
        \App\Pkg::create(['state_id'=>	11	, 'pkg'=>'	PKG Mukah	']);
        \App\Pkg::create(['state_id'=>	11	, 'pkg'=>'	PKG Dalat	']);
        \App\Pkg::create(['state_id'=>	11	, 'pkg'=>'	PKG Miri	']);
        \App\Pkg::create(['state_id'=>	11	, 'pkg'=>'	PKG Bintulu	']);
        \App\Pkg::create(['state_id'=>	11	, 'pkg'=>'	PKG Subis	']);
        \App\Pkg::create(['state_id'=>	11	, 'pkg'=>'	PKG Baram	']);
        \App\Pkg::create(['state_id'=>	11	, 'pkg'=>'	PKG Limbang	']);
        \App\Pkg::create(['state_id'=>	11	, 'pkg'=>'	PKG Lawas	']);
        \App\Pkg::create(['state_id'=>	11	, 'pkg'=>'	PKG Sarikei	']);
        \App\Pkg::create(['state_id'=>	11	, 'pkg'=>'	PKG Daro	']);
        \App\Pkg::create(['state_id'=>	11	, 'pkg'=>'	PKG Meradong	']);
        \App\Pkg::create(['state_id'=>	11	, 'pkg'=>'	PKG Julau	']);
        \App\Pkg::create(['state_id'=>	11	, 'pkg'=>'	PKG Kapit	']);
        \App\Pkg::create(['state_id'=>	11	, 'pkg'=>'	PKG Song	']);
        \App\Pkg::create(['state_id'=>	11	, 'pkg'=>'	PKG Belaga	']);
        \App\Pkg::create(['state_id'=>	13	, 'pkg'=>'	PKG Binjai	']);
        \App\Pkg::create(['state_id'=>	13	, 'pkg'=>'	PKG Bukit Besar	']);
        \App\Pkg::create(['state_id'=>	13	, 'pkg'=>'	PKG Paka	']);
        \App\Pkg::create(['state_id'=>	13	, 'pkg'=>'	PKG Tengkawang	']);
        \App\Pkg::create(['state_id'=>	13	, 'pkg'=>'	PKG Bukit Besi	']);
        \App\Pkg::create(['state_id'=>	13	, 'pkg'=>'	PKG Seri Payong	']);
        \App\Pkg::create(['state_id'=>	13	, 'pkg'=>'	PKG Tok Jiring	']);
        \App\Pkg::create(['state_id'=>	13	, 'pkg'=>'	PKG Permaisuri	']);
        \App\Pkg::create(['state_id'=>	13	, 'pkg'=>'	PKG Marang	']);
        \App\Pkg::create(['state_id'=>	13	, 'pkg'=>'	PKG Bukit Payong	']);
        \App\Pkg::create(['state_id'=>	13	, 'pkg'=>'	PKG Jerteh	']);
        \App\Pkg::create(['state_id'=>	13	, 'pkg'=>'	PKG Raja	']);
        \App\Pkg::create(['state_id'=>	13	, 'pkg'=>'	PKG Pulau Serai	']);
        \App\Pkg::create(['state_id'=>	13	, 'pkg'=>'	PKG Seri Dungun	']);
        \App\Pkg::create(['state_id'=>	13	, 'pkg'=>'	PKG Manir	']);
        \App\Pkg::create(['state_id'=>	13	, 'pkg'=>'	PKG Kemasek	']);
        \App\Pkg::create(['state_id'=>	13	, 'pkg'=>'	PKG Cheneh Baru	']);
        \App\Pkg::create(['state_id'=>	13	, 'pkg'=>'	PKG Mengabang Telipot	']);
        \App\Pkg::create(['state_id'=>	13	, 'pkg'=>'	PKG Peroh	']);
        \App\Pkg::create(['state_id'=>	13	, 'pkg'=>'	PKG Kuala Berang	']);
        \App\Pkg::create(['state_id'=>	13	, 'pkg'=>'	PKG Langkap	']);
        \App\Pkg::create(['state_id'=>	13	, 'pkg'=>'	PKG Durian Burong	']);

    }
}
